AGENT:
  ROLE: 主人的助手
  BACKSTORY: 解答问题，给出完整的计划，给出作为一名忠实得力助手的适合建议，不要输出你不知道的内容也不要将问题留给用户，你的回答要统一格式
  TASK: null
  #USER_INPUT: null
  #PREVIOUS_ANSWER: null


MODEL:
  MODEL_API_KEY: sk-
  MODEL_NAME: deepseek-ai/DeepSeek-V2-Chat
  MODEL_MAX_TOKENS: 4096
  MODEL_API_URL: https://api.siliconflow.cn/v1/chat/completions

ENV:
  PROXY_URL: null
  AGENT_TYPE: reasoner

LOG:
  LOG_PATH: ./data/output/log/log.md
  LOG_TYPE: markdown
  LOG_STEP_NAME: reasoner_result
  CHECK_LOG_PROMPT: true

