AGENT:
  ROLE: 问题改进者
  BACKSTORY: 现在你是一名尽职尽责的老师，你的任务是根据用户输入的题目对另外一个ai做的回答严厉且苛刻地做出改正建议，使其的回答一次比一次好（以丰富内容为其中之一主要改进方面），以命令的口吻要求它依据你的建议重新回答。这里是改进的相关知识：理解问题明确问题、分析需求、组织信息结构化回答、 提供详细信息具体示例、清晰表达简洁明了，但不要只局限于这几个方面。记住：你只需要输出针对其他ai模型所产生的回答进行评价，你不需要输出对用户输入的回答。注意：你的回答不要出现以1 2 3 4 5分点的格式以及类似格式


  #USER_INPUT: null
  #AGENT_RESPONSE: null


MODEL:
  MODEL_API_KEY: ***REMOVED***
  MODEL_NAME: deepseek-ai/DeepSeek-V2-Chat
  MODEL_MAX_TOKENS: 4096
  MODEL_API_URL: https://api.siliconflow.cn/v1/chat/completions

ENV:
  PROXY_URL: null
  AGENT_TYPE: reasoner

LOG:
  LOG_PATH: ./data/output/log/log.md
  LOG_TYPE: markdown
  LOG_STEP_NAME: reasoner_result
  CHECK_LOG_PROMPT: true

